baseURL = "https://gabrielopesantos.github.io"
languageCode = "en-us"
title = "Gabriel Santos"
copyright = "© Gabriel Santos"
theme = "archie"

[params]
	favicon="favicon.ico"
	subtitle="Software Engineer at OutSystems"
	mode="dark"
	useCDN=true

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/gabrielopesantos"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/jgabrielsantos"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Contacts"
url = "/contacts"
weight = 2

[[menu.main]]
name = "Portfolio"
url = "/portfolio"
weight = 3

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 4